exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("inventory")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("inventory").insert([
        {
          id: 1,
          name: "Boston Crab Meat",
          sku: "F3zJAGHEJx",
          supplierId: 1,
          status: "available",
          inStock: 18.4,
          price: 123,
        },
        {
          id: 2,
          name: "Grandma's Boysenberry Spread",
          sku: "cGiQLTFTjK",
          supplierId: 2,
          status: "available",
          inStock: 120,
          price: 25,
        },
        {
          id: 3,
          name: "Tofu",
          sku: "4NH6Zd2A2m",
          supplierId: 3,
          status: "available",
          inStock: 235,
          price: 23.25,
        },
        {
          id: 4,
          name: "Steeleye Stout",
          sku: "JIXCXTlYGl",
          supplierId: 4,
          status: "backordered",
          inStock: 20,
          price: 18,
        },
        {
          id: 5,
          name: "Sir Rodney's Scones",
          sku: "4fcGF5IU8g",
          supplierId: 5,
          status: "backordered",
          inStock: 10,
          price: 3,
        },
        {
          id: 6,
          name: "Sir Rodney's Marmalade",
          sku: "l5p73rFeTK",
          supplierId: 1,
          status: "available",
          inStock: 81,
          price: 40,
        },
        {
          id: 7,
          name: "Chai",
          sku: "BEgBUgdbrY",
          supplierId: 2,
          status: "delayed",
          inStock: 39,
          price: 18,
        },
        {
          id: 8,
          name: "Outback Lager",
          sku: "fJMQMrTbHP",
          supplierId: 3,
          status: "available",
          inStock: 15,
          price: 15,
        },
        {
          id: 9,
          name: "Northwoods Cranberry Sauce",
          sku: "j9cRDxnr0F",
          supplierId: 4,
          status: "discontinued",
          inStock: 6,
          price: 40,
        },
        {
          id: 10,
          name: "Laughing Lumberjack Lager",
          sku: "LFMadtx3wx",
          supplierId: 5,
          status: "available",
          inStock: 52,
          price: 14,
        },
        {
          id: 11,
          name: "Uncle Bob's Organic Dried Pears",
          sku: "cP3iKxMHL1",
          supplierId: 1,
          status: "discontinued",
          inStock: 15,
          price: 30,
        },
        {
          id: 12,
          name: "Jack's New England Clam Chowder",
          sku: "8Wo7P1XnLK",
          supplierId: 2,
          status: "available",
          inStock: 85,
          price: 9.65,
        },
        {
          id: 13,
          name: "Louisiana Fiery Hot Pepper Sauce",
          sku: "yqMKuFbWZB",
          supplierId: 3,
          status: "available",
          inStock: 76,
          price: 21.05,
        },
        {
          id: 14,
          name: "Ipoh Coffee",
          sku: "pzc9Q2SWlT",
          supplierId: 4,
          status: "backordered",
          inStock: 17,
          price: 46,
        },
        {
          id: 15,
          name: "Aniseed Syrup",
          sku: "FRvM8Gt3pd",
          supplierId: 5,
          status: "available",
          inStock: 13,
          price: 10,
        },
        {
          id: 16,
          name: "Ravioli Angelo",
          sku: "lfNwDVVTRv",
          supplierId: 1,
          status: "available",
          inStock: 36,
          price: 19.5,
        },
        {
          id: 17,
          name: "Vegie-spread",
          sku: "pzvg1gq4ee",
          supplierId: 2,
          status: "available",
          inStock: 24,
          price: 43.9,
        },
        {
          id: 18,
          name: "Louisiana Hot Spiced Okra",
          sku: "uxjJYIU5Ab",
          supplierId: 3,
          status: "discontinued",
          inStock: 4,
          price: 17,
        },
        {
          id: 19,
          name: "Manjimup Dried Apples",
          sku: "5pCgHHIBXB",
          supplierId: 4,
          status: "delayed",
          inStock: 20,
          price: 53,
        },
        {
          id: 20,
          name: "Chef Anton's Gumbo Mix",
          sku: "YRhgPiyd5L",
          supplierId: 5,
          status: "available",
          inStock: "25",
          price: 21.35,
        },
      ]);
    });
};
