exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("users")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("users").insert([
        {
          id: 1,
          username: "nathansl2003",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Nathan",
          lastName: "Loveless",
          address: "150 Main Street Apt. 22",
          city: "Montpelier",
          state: "Vermont",
          zipcode: "05663",
          email: "nathansl2003@cmail.com",
          status: "active",
          role: "admin",
        },
        {
          id: 2,
          username: "jsmith",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Jane",
          lastName: "Smith",
          address: "2235 Darwin Ln.",
          city: "Omaha",
          state: "Nebraska",
          zipcode: "34106",
          email: "jsmith@cmail.com",
          status: "active",
          role: "execute",
        },
        {
          id: 3,
          username: "dharvey",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Doug",
          lastName: "Harvey",
          address: "33 Short Ave.",
          city: "Puyallup",
          state: "Washington",
          zipcode: "65195",
          email: "dharvey@cmail.com",
          status: "inactive",
          role: "none",
        },
        {
          id: 4,
          username: "jallen",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Jill",
          lastName: "Allen",
          address: "96 Lovers Ln.",
          city: "Riverton",
          state: "Vermont",
          zipcode: "05410",
          email: "jallen@cmail.com",
          status: "inactive",
          role: "none",
        },
        {
          id: 5,
          username: "jmiller",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Jake",
          lastName: "Miller",
          address: "144 Rt. 76",
          city: "Tuscon",
          state: "Arizona",
          zipcode: "33150",
          email: "jmiller@cmail.com",
          status: "inactive",
          role: "none",
        },
        {
          id: 6,
          username: "rcross",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Robert",
          lastName: "Cross",
          address: "15 Circle Ct.",
          city: "Ludlow",
          state: "Massachusetts",
          zipcode: "14193",
          email: "rcross@cmail.com",
          status: "inactive",
          role: "none",
        },
        {
          id: 7,
          username: "rmason",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Roger",
          lastName: "Mason",
          address: "1315 Manhatten Ave. Suite 305",
          city: "New York",
          state: "New York",
          zipcode: "55610",
          email: "rmason@cmail.com",
          status: "active",
          role: "execute",
        },
        {
          id: 8,
          username: "asmithfield",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Anita",
          lastName: "Smithfield",
          address: "1005 Grey Lake Dr.",
          city: "Lansing",
          state: "Michigan",
          zipcode: "91706",
          email: "asmithfield@cmail.com",
          status: "active",
          role: "read",
        },
        {
          id: 9,
          username: "bcarson",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Ben",
          lastName: "Carson",
          address: "4961 Rupert St.",
          city: "Boston",
          state: "Massachusetts",
          zipcode: "14161",
          email: "bcarson@cmail.com",
          status: "active",
          role: "execute",
        },
        {
          id: 10,
          username: "krucker",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Kim",
          lastName: "Rucker",
          address: "55 Juniper Ave.",
          city: "Boise",
          state: "Idaho",
          zipcode: "29931",
          email: "krucker@cmail.com",
          status: "active",
          role: "read",
        },
        {
          id: 11,
          username: "jmoen",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Jack",
          lastName: "Moen",
          address: "19 Jackob St.",
          city: "Johnson",
          state: "Vermont",
          zipcode: "05114",
          email: "jmoen@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 12,
          username: "gcollard",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "George",
          lastName: "Collard",
          address: "505 Rt. 3",
          city: "LaPorte",
          state: "Indiana",
          zipcode: "75547",
          email: "gcollard@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 13,
          username: "mdarby",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Mitch",
          lastName: "Darby",
          address: "196 Blane Ln.",
          city: "Norwalk",
          state: "Ohio",
          zipcode: "47223",
          email: "mdarby@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 14,
          username: "cdaniels",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Charlie",
          lastName: "Daniels",
          address: "44 Tower Ln. Apt. 401",
          city: "Austin",
          state: "Texas",
          zipcode: "38143",
          email: "cdaniels@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 15,
          username: "kreiner",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Keith",
          lastName: "Reiner",
          address: "87 Main St.",
          city: "Wellington",
          state: "Alabama",
          zipcode: "07651",
          email: "kreiner@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 16,
          username: "mrose",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Mary",
          lastName: "Rose",
          address: "1555 Crooked Ct.",
          city: "Ft. Lauderdale",
          state: "Florida",
          zipcode: "00561",
          email: "mrose@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 17,
          username: "njenkins",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Natalie",
          lastName: "Jenkins",
          address: "962 Macon Ave.",
          city: "Portland",
          state: "Oregon",
          zipcode: "66294",
          email: "njenkins@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 18,
          username: "porion",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Pam",
          lastName: "Orion",
          address: "18 Little Stream Rd.",
          city: "Albourgh",
          state: "New York",
          zipcode: "81554",
          email: "porion@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 19,
          username: "schan",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Steven",
          lastName: "Chan",
          address: "88 Plum Ave.",
          city: "Norfolk",
          state: "Virginia",
          zipcode: "40084",
          email: "schan@cmail.com",
          status: "pending",
          role: "none",
        },
        {
          id: 20,
          username: "tbest",
          password:
            "$2a$05$Bkke.wlmN2csDslLpF.vSuqJ7LLxQVYAwcTeCp7xdpcLLftMZGrVy",
          firstName: "Tom",
          lastName: "Best",
          address: "441 Mondock Rd.",
          city: "Atlanta",
          state: "Georgia",
          zipcode: "50911",
          email: "tbest@cmail.com",
          status: "pending",
          role: "none",
        },
      ]);
    });
};
